######################################################################
# Automatically generated by qmake (2.01a) Fri Aug 1 19:38:51 2008
######################################################################

TEMPLATE = app
TARGET = 
INCLUDEPATH += . include ../include
MOC_DIR = generated
UI_DIR = generated
OBJECTS_DIR = intermediates
DESTDIR = release
LIBS += -L../release -lTwit


# Input
HEADERS += include/example.h
FORMS += ui/example.ui
SOURCES += src/example.cpp src/main.cpp

